name: Generate artifacts

on:
    push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
          - name: Install Cowsay
            run: sudo apt-get install cowsay -y
          - name: Execute Cowsay CMD
            run: cowsay -f dragon "Run for Cover, I am DRAGON .... ROAR" >> dragon.txt
          - name: Upload Dragon txt
            uses: actions/upload-artifact@v3
            with:
              name: dragon-txt-file
              path: dragon.txt

    test_job_2:
        runs-on: ubuntu-latest
        needs: build_job_1
        steps:
            - name: Download Dragon txt
              uses: actions/download-artifact@v3
              with:
                name: dragon-txt-file
                path: dragon.txt
