name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome Message
          run: echo "My first GitHub Actions job"
        - name: List Files
          run: ls -al
        - name: Print Readme
          run: cat README.md