name: Generate ASCII

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: List all files
          run: ls -al

        - name: Execute Shell Script
          run: |
            chmod a+x ascii-script.sh
            ./ascii-script.sh