name: workflow filters and activities
on:
    workflow_dispatch:
    # schedule:
    #     - cron: "*/5 * * * *"
    push:
      branches-ignore:
        - feature/*
        - test/**
    pull_request:
        types: 
          - opened
          - closed
        paths-ignore:
          - README.md
        branches:
          - main
        # branches-ignore: # branches and branches_ignore mutually exclusive
        #   - feature/*
        #   - test/*

jobs:
    hello:
      runs-on: ubuntu-latest
      steps:
        - name: event name 
          run: echo this workflow/job/step is executed for event type - ${{ github.event_name }}

